default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: hierropagotto
  password: Home131313
  host: localhost
  port: 5433

development:
  <<: *default
  database: final_project_development

test:
  <<: *default
  database: final_project_test

production:
  <<: *default
  database: final_project_production
  username: final_project
  password: <%= ENV["FINAL_PROJECT_DATABASE_PASSWORD"] %>

